### ISSUE TITLE
update https://demo.websheets.co/

### ISSUE THREAD

**Issue by muescha** [tengkuhafidz/WebSheets-Listing-Page#4]
brand name change in 27b52904e72ab2b3d2279e7a2e9774526e776010 is not on website: https://demo.websheets.co/
<img width="297" alt="Bildschirmfoto 2020-07-29 um 16 10 43" src="https://user-images.githubusercontent.com/184316/88810775-16809500-d1b6-11ea-97b7-f2ed8d29dad0.png">

**Comment by tengkuhafidz** [comment]
Thank you!

**Comment by tengkuhafidz** [comment]
Just curious, how did you find this repo btw? @muescha

**Comment by muescha** [comment]
> Just curious, how did you find this repo btw? @muescha
your PR to gatsby showcase

**Comment by tengkuhafidz** [comment]
I see. Done! Thank you for the nudge. @muescha 

Is there anywhere I can contact you to ask why my starter submission is stuck btw? Twitter maybe?

Particularly for this repo? It does not seem to fail on my end. https://github.com/gatsbyjs/gatsby/pull/26070

**Comment by muescha** [comment]
Same name on Twitter. I should update my profile. 

But Submissions always take a while

**Comment by tengkuhafidz** [comment]
I see. Thank you for sharing! Appreciate it.
